title:             Clean Blog
email:             zj224543@gmail
description:       博客测试页
author:            标题抬头也
baseurl:            
url:                

# Social Profiles
twitter_username:  @zjfane
github_username:    
facebook_username:  

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
